openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0

paths:
  x-kusk:
    upstream:
      service:
        name: smart-home-gw-svc
        namespace: default
        port: 8080
  path:
    /device:
      put:
        x-kusk:
          upstream:
            service:
              name: smart-home-monolith
              port: 8083
    /telemetry/latest:
      get:
        x-kusk:
          upstream:
            service:
              name: smart-home-monolith
              port: 8083