@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the smart home system")

System(SmartHomeSystem, "SmartHome System", "Heating control and temperature monitoring in a smart home")

System_Ext(sensors, "Sensors API", "Датчики")

Rel(user, SmartHomeSystem, "включать/выключать отопление, устанавливать температуру")
Rel(SmartHomeSystem, sensors, "управление датчиками")

@enduml