@startuml
title SmartHome Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the smart home system")
System_Ext(sensors, "Sensors API", "Датчики")
System(SmartHomeSystem, "SmartHome System", "Heating control and temperature monitoring in a smart home")

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(ApiGateway, "ApiGateway Application", "Java, Spring", "Handles user interactions")
  Container(SmartHomeMonolith, "Smart Home Application", "Java, Spring", "Handles user interactions")
  Container(DeviceApp, "Device Management Application", "Java, Spring", "Handles user interactions")
  Container(TelemetryApp, "Telemetry Application", "Java, Spring", "Handles user interactions")
  Container(DeviceDatabase, "Database", "PostgreSQL", "Stores user data and schedules")
  Container(TelemetryDatabase, "Database", "PostgreSQL", "Stores user data and schedules")
}

Rel(user, ApiGateway, "включать/выключать отопление, устанавливать температуру")
Rel(ApiGateway, SmartHomeMonolith, "update")
Rel(SmartHomeMonolith, DeviceApp, "update")
Rel(SmartHomeMonolith, TelemetryApp, "update")
Rel(DeviceApp,DeviceDatabase,"Reads/Writes device data")
Rel(TelemetryApp,TelemetryDatabase,"Reads/Writes device data")
Rel(DeviceApp,sensors,"управление датчиками")

@enduml